-- KEYCLOAK
CREATE DATABASE IF NOT EXISTS `keycloak` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'keycloak'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON `keycloak`.* TO 'keycloak'@'%';

-- ACCOUNT_SERVICE
CREATE DATABASE IF NOT EXISTS `accountservice` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'account'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON `accountservice`.* TO 'account'@'%';

-- ATTEMPT_SERVICE
CREATE DATABASE IF NOT EXISTS `attemptservice` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'attempt'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON `attemptservice`.* TO 'attempt'@'%';

-- TEST_SERVICE
CREATE DATABASE IF NOT EXISTS `testservice` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'test'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON `testservice`.* TO 'test'@'%';

-- COMMENT_SERVICE
CREATE DATABASE IF NOT EXISTS `commentservice` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'comment'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON `commentservice`.* TO 'comment'@'%';

-- CHATBOT
CREATE DATABASE IF NOT EXISTS `chatbot` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'chatbot'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON `chatbot`.* TO 'chatbot'@'%';

-- NOTIFICATION_SERVICE
CREATE DATABASE IF NOT EXISTS `notification` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'notification'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON `notification`.* TO 'notification'@'%';